import Link from "next/link";
import { REPORT_PRICE_LABEL } from "@/lib/preview";
import {
  LEGAL_BUSINESS_DESCRIPTION,
  LEGAL_COMPANY_NAME,
  SITE_NAME,
} from "@/lib/site";
import { LegalContactBlock } from "@/lib/legal/contact";

interface TermsOfUseContentProps {
  contactEmail: string | null;
  siteUrl: string;
}

export function TermsOfUseContent({ contactEmail, siteUrl }: TermsOfUseContentProps) {
  const privacyUrl = `${siteUrl}/privacy`;
  const domain = siteUrl.replace(/^https?:\/\//, "");

  return (
    <>
      <p>
        The website located at <a href={siteUrl}>{domain}</a> (the &quot;Site&quot;) is owned and
        operated by {LEGAL_COMPANY_NAME} (&quot;Company,&quot; &quot;us,&quot; &quot;our,&quot; or
        &quot;we&quot;). Certain features of the Site may be subject to additional guidelines or
        rules posted on the Site, which are incorporated by reference into these Terms.
      </p>
      <p>
        These Terms of Use (&quot;Terms&quot;) govern your use of the Site. By accessing or using
        the Site, you agree to these Terms on behalf of yourself or the entity you represent, and
        you confirm that you have the authority to do so. You must be at least 18 years old to use
        the Site. If you do not agree to these Terms, please do not use the Site.
      </p>
      <p>
        <strong>IMPORTANT — PLEASE READ SECTION 11 CAREFULLY.</strong> It contains an agreement to
        resolve disputes through binding individual arbitration instead of in court, and includes a
        waiver of class action rights and jury trial rights. You have 30 days to opt out of the
        arbitration agreement, as further described in Section 11.
      </p>

      <h2>1. Accounts</h2>
      <p>
        The Site does not require you to create an account to use the free diagnostic preview. If we
        offer optional account or registration features in the future, you agree to provide accurate
        and complete information and to keep that information current. You are responsible for
        keeping any login credentials confidential and for all activity that occurs under your
        account. We may suspend or terminate access as described in Section 8.
      </p>

      <h2>2. Access to the Site</h2>
      <p>
        <strong>License.</strong> Subject to these Terms, we grant you a limited, non-exclusive,
        non-transferable, revocable license to access and use the Site for your own personal or
        internal business purposes.
      </p>
      <p>
        <strong>Restrictions.</strong> You may not: (i) license, sell, rent, lease, transfer,
        assign, distribute, or commercially exploit the Site or any content on it; (ii) modify,
        create derivative works from, disassemble, reverse-compile, or reverse-engineer any part of
        the Site; (iii) access the Site in order to build a similar or competing product or
        service; or (iv) copy, reproduce, distribute, republish, download, display, post, or transmit
        any part of the Site except as expressly permitted by these Terms.
      </p>
      <p>
        <strong>Changes to the Site.</strong> We may modify, suspend, or discontinue the Site (or
        any part of it) at any time, with or without notice. We are not liable to you or any third
        party for any such modification, suspension, or discontinuation.
      </p>
      <p>
        <strong>Ownership.</strong> All intellectual property rights in the Site and its content
        belong to Company or its suppliers. These Terms do not transfer any ownership rights to you,
        except for the limited access rights in this section.
      </p>
      <p>
        <strong>Feedback.</strong> If you share feedback or suggestions about the Site with us, you
        grant us a perpetual, irrevocable, worldwide, non-exclusive, fully-paid, royalty-free license
        to use that feedback freely, in any manner and for any purpose, without attribution.
      </p>

      <h2>3. Diagnostic service and paid reports</h2>
      <p>
        {SITE_NAME} provides a {LEGAL_BUSINESS_DESCRIPTION}. You can complete a free preview. You may
        pay a one-time fee (currently {REPORT_PRICE_LABEL}) to unlock a fuller written report with
        category breakdowns and recommendations. The optional Revenue Leak Check Chrome extension
        performs a page scan of the tab you invoke it on; it is not the paid report.
      </p>
      <p>
        <strong>Not professional advice.</strong> The diagnostic, scores, dollar estimates, and
        recommendations are <strong>informational only</strong>. They are generated by rules and
        formulas applied to your answers — not by a human consultant reviewing your books. They are{" "}
        <strong>not</strong> financial, accounting, tax, or legal advice. Do not make major business
        decisions based only on this report.
      </p>
      <p>
        <strong>Estimates are approximate.</strong> Revenue loss figures are directional estimates.
        They depend on the accuracy of your answers and assumptions built into our models. Actual
        results will vary. We do not guarantee that fixing any issue will recover any particular
        amount of revenue.
      </p>
      <p>
        <strong>Your answers.</strong> You are responsible for providing answers that are as
        accurate as you can make them.
      </p>
      <p>
        <strong>Payment.</strong> Paid reports are sold as a <strong>one-time purchase</strong>
        (currently {REPORT_PRICE_LABEL}). Checkout is handled by Stripe. By paying, you also agree
        to Stripe&apos;s terms where applicable. Prices may change for future purchases; the price
        shown at checkout is what you pay.
      </p>
      <p>
        <strong>Refunds.</strong> We offer a <strong>7-day money-back guarantee</strong> on the paid
        report. If you are unhappy with your purchase, contact us within 7 days of payment and we
        will refund you. We may ask for your email or payment details to locate the transaction.
        After a refund, access to the paid report may be revoked.
      </p>
      <p>
        <strong>Report access.</strong> After purchase, you can view your report on the Site and may
        receive an email with a link. Links include an access token and can stop working after a
        period of time or if we delete the underlying record. Save or print your report if you need
        a long-term copy.
      </p>

      <h2>4. Privacy</h2>
      <p>
        Your use of the Site is also governed by our Privacy Policy, which is available at{" "}
        <Link href="/privacy">{privacyUrl}</Link> and is incorporated into these Terms by reference.
      </p>
      <p>
        <strong>Cookies and tracking technologies.</strong> The Site may use cookies, web beacons,
        pixels, and similar tracking technologies to collect information about your use of the Site
        when you consent via our cookie banner. For details, please refer to our{" "}
        <Link href="/privacy">Privacy Policy</Link>.
      </p>

      <h2>5. Indemnification</h2>
      <p>
        You agree to defend, indemnify, and hold harmless Company and its officers, employees, and
        agents from any claims and reasonable costs or attorneys&apos; fees arising out of (i) your
        use of the Site, (ii) your violation of these Terms, or (iii) your violation of any
        applicable law or regulation. We may assume control of the defense of any such claim at your
        expense, and you agree to cooperate with our defense.
      </p>

      <h2>6. Third-party services</h2>
      <p>
        The Site may include links to or integrations with third-party websites or services
        (collectively, &quot;Third-Party Services&quot;), including Stripe for payments and
        analytics or advertising tools when configured. We do not control, endorse, or take
        responsibility for any Third-Party Services. You use all Third-Party Services at your own
        risk, and the applicable third party&apos;s own terms and privacy practices will apply.
      </p>

      <h2>7. Disclaimers</h2>
      <p>
        THE SITE AND DIAGNOSTIC OUTPUT ARE PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE.&quot;
        TO THE FULLEST EXTENT PERMITTED BY LAW, COMPANY AND ITS SUPPLIERS DISCLAIM ALL WARRANTIES,
        EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
        PURPOSE, TITLE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SITE WILL BE UNINTERRUPTED,
        ERROR-FREE, SECURE, OR FREE OF VIRUSES OR HARMFUL CODE, OR THAT DIAGNOSTIC ESTIMATES WILL BE
        ACCURATE. WHERE APPLICABLE LAW REQUIRES WARRANTIES, THEY ARE LIMITED TO 90 DAYS FROM YOUR
        FIRST USE.
      </p>

      <h2>8. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW: (A) COMPANY AND ITS SUPPLIERS WILL NOT BE LIABLE FOR
        ANY LOST PROFITS, LOST DATA, COSTS OF SUBSTITUTE PRODUCTS, OR ANY INDIRECT, CONSEQUENTIAL,
        INCIDENTAL, SPECIAL, EXEMPLARY, OR PUNITIVE DAMAGES ARISING FROM OR RELATED TO THESE TERMS
        OR YOUR USE OF (OR INABILITY TO USE) THE SITE; AND (B) OUR TOTAL LIABILITY TO YOU FOR ANY
        CLAIM ARISING UNDER THESE TERMS IS CAPPED AT THE GREATER OF (i) $50 USD AND (ii) THE AMOUNT
        PAID TO COMPANY BY YOU UNDER THESE TERMS IN THE SIX MONTHS PRIOR TO THE INCIDENT GIVING RISE
        TO THE CLAIM. THE EXISTENCE OF MULTIPLE CLAIMS DOES NOT INCREASE THIS CAP.
      </p>

      <h2>9. Term and termination</h2>
      <p>
        These Terms remain in effect while you use the Site. We may suspend or terminate your access
        at any time and for any reason, including if we believe you have violated these Terms. We are
        not liable to you for any such termination. Upon termination, provisions that by their nature
        should survive will survive.
      </p>

      <h2>10. State-specific legal notices</h2>
      <p>
        If you are a California resident, you may have additional rights under the California
        Consumer Privacy Act (as amended by the California Privacy Rights Act). For details, please
        see our <Link href="/privacy">Privacy Policy</Link>.
      </p>
      <p>
        If you are a Colorado, Connecticut, Virginia, or other U.S. state resident with a
        comprehensive consumer privacy law applicable to us, you may have additional rights as
        described in our <Link href="/privacy">Privacy Policy</Link>.
      </p>
      {contactEmail ? (
        <p>
          Nevada residents may contact us at{" "}
          <a href={`mailto:${contactEmail}`}>{contactEmail}</a> regarding opt-out rights under
          Nevada law.
        </p>
      ) : null}

      <h2>11. General</h2>
      <p>
        <strong>Changes to Terms.</strong> We may update these Terms from time to time. If we make
        material changes, we may notify you by email (at the address on file) or by a prominent
        notice on the Site. Your continued use of the Site after notice of changes means you accept
        the updated Terms.
      </p>
      <p>
        <strong>Governing law.</strong> These Terms and any dispute arising out of or related to
        these Terms or the Site will be governed by the laws of the State of California, without
        regard to its conflict-of-law principles. For any claim not subject to the arbitration
        provisions in Section 12, you and Company irrevocably consent to the exclusive jurisdiction
        and venue of the state and federal courts located in California. Either party may bring an
        action for injunctive or other equitable relief to protect intellectual property rights, or
        an individual action in small claims court for claims within that court&apos;s jurisdictional
        limits.
      </p>
      <p>
        <strong>Electronic communications.</strong> By using the Site, you consent to receiving
        communications from us electronically (by email or notices posted on the Site).
      </p>
      <p>
        <strong>Entire agreement.</strong> These Terms (together with the Privacy Policy and any
        other policies referenced herein) are the entire agreement between you and Company regarding
        your use of the Site.
      </p>
      <p>
        <strong>Copyright.</strong> Copyright © {new Date().getFullYear()} {LEGAL_COMPANY_NAME}. All
        rights reserved.
      </p>
      <p>
        <strong>Contact information.</strong>
      </p>
      <LegalContactBlock contactEmail={contactEmail} purpose="Questions about these Terms or refund requests" />

      <h2>12. Dispute resolution</h2>
      <p>
        <strong>Please read this section carefully.</strong> It affects your legal rights, including
        your right to sue in court and your right to a jury trial.
      </p>
      <p>
        <strong>Applicability.</strong> Except as described below, you and Company agree to resolve
        all disputes arising out of or relating to the Site, its services, or these Terms through
        binding individual arbitration — not in court. Exceptions include: (i) claims that qualify
        for small claims court, brought on an individual basis; and (ii) requests for equitable relief
        related to intellectual property. This arbitration agreement applies to all claims,
        including those that arose before you agreed to these Terms.
      </p>
      <p>
        <strong>Try to resolve first.</strong> Before starting arbitration, the parties agree to try
        to resolve the dispute informally. The party raising the dispute must send written notice (an
        &quot;Informal Notice&quot;) to the other party. Within 45 days of receiving that Informal
        Notice, the parties will meet by phone or video in good faith to try to work things out. If
        the informal dispute resolution process does not resolve the dispute within 60 days, either
        party may start arbitration.
      </p>
      {contactEmail ? (
        <p>
          Company&apos;s notice address for Informal Notices:{" "}
          <a href={`mailto:${contactEmail}`}>{contactEmail}</a>.
        </p>
      ) : (
        <p>
          Company&apos;s notice address for Informal Notices: reply to any email you received from
          us about your report.
        </p>
      )}
      <p>
        <strong>Arbitration rules.</strong> Arbitrations will be administered by JAMS (
        <a href="https://www.jamsadr.com" target="_blank" rel="noopener noreferrer">
          www.jamsadr.com
        </a>
        ). Claims under $250,000 (excluding fees and interest) will use JAMS&apos; Streamlined
        Arbitration Rules; larger claims will use JAMS&apos; Comprehensive Arbitration Rules. Unless
        the parties agree otherwise, arbitration will be conducted in the county where you live. All
        arbitration materials and documents are confidential.
      </p>
      <p>
        <strong>Waiver of jury trial.</strong> BY AGREEING TO ARBITRATION, YOU AND COMPANY WAIVE THE
        RIGHT TO A TRIAL BY JUDGE OR JURY FOR ALL COVERED CLAIMS.
      </p>
      <p>
        <strong>Waiver of class actions.</strong> ALL DISPUTES MUST BE BROUGHT ON AN INDIVIDUAL
        BASIS. NEITHER YOU NOR COMPANY MAY BRING CLAIMS AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS,
        REPRESENTATIVE, OR COLLECTIVE PROCEEDING. The arbitrator may only award relief on an
        individual basis.
      </p>
      <p>
        <strong>Opt-out.</strong> You may opt out of this arbitration agreement within 30 days of
        first accepting these Terms by sending written notice to us at the contact address above.
        Your notice must include your name, address, and a clear statement that you wish to opt out.
        Opting out does not affect any other part of these Terms.
      </p>

      <p className="text-sm text-slate-600">
        These Terms are adapted from templates by{" "}
        <a
          href="https://github.com/General-Legal/legal-templates"
          target="_blank"
          rel="noopener noreferrer"
        >
          General Legal
        </a>{" "}
        (CC0). See also our <Link href="/privacy">Privacy Policy</Link>.
      </p>
    </>
  );
}
