// AUTO-GENERATED by scripts/generate-blog.mjs — do not edit by hand.
import type { BlogManifest } from "./types";

export const blogManifest: BlogManifest = {
  "author": {
    "name": "Revenue Leak",
    "tagline": "Practical revenue leakage research for operators and founders.",
    "bio": "Revenue Leak publishes actionable guidance on revenue leakage, funnel performance, and billing recovery for SaaS, ecommerce, agency, and service businesses. Articles and the diagnostic use a structured six-category framework and published industry benchmarks—designed to help teams prioritize fixes quickly.",
    "credentials": [
      "Six-category leakage framework covering acquisition, response, conversion, retention, billing, and expansion",
      "Benchmarks aligned with widely cited industry ranges and funnel performance metrics",
      "Documented questionnaire-based methodology with transparent scoring assumptions",
      "Content aligned with the Revenue Leak diagnostic for consistent guidance across the site"
    ],
    "methodology": [
      {
        "title": "Structured framework",
        "text": "Every article maps to one or more stages of the customer journey—so readers can connect advice to measurable funnel steps."
      },
      {
        "title": "Benchmark-driven",
        "text": "Guidance references published ranges and operator best practices rather than anecdote, with clear steps to estimate dollar impact from your own numbers."
      },
      {
        "title": "Action-first",
        "text": "Recommendations are ranked by estimated impact and implementation effort, matching the prioritization logic in the Revenue Leak diagnostic."
      }
    ],
    "disclaimer": "Revenue Leak provides directional estimates and educational content. It is not a substitute for formal financial, legal, tax, or audit advice. Always validate material decisions with qualified professionals.",
    "sameAs": [
      "https://www.revenueleak.report"
    ]
  },
  "pillars": [
    {
      "slug": "billing-recovery",
      "title": "Billing & Recovery",
      "description": "Stop losing recurring revenue to failed payments, dunning gaps, and billing errors — recovery playbooks for SaaS and subscriptions.",
      "published": "2026-07-16",
      "postSlugs": [
        "failed-payment-recovery",
        "subscription-billing-leaks"
      ],
      "keywords": [
        "failed payment recovery",
        "dunning",
        "involuntary churn",
        "billing leakage",
        "subscription revenue leak"
      ],
      "faq": [
        {
          "q": "What is failed payment recovery?",
          "a": "The process of retrying declined charges, emailing customers to update cards, and recovering revenue from involuntary churn — often the highest-ROI billing fix."
        },
        {
          "q": "How quickly should you retry failed payments?",
          "a": "Most teams use 3–4 retries over two weeks, plus dunning emails with a one-click update link. Smart retry timing improves recovery rates."
        }
      ],
      "intro": "Billing leaks are silent: cards fail, invoices slip, and MRR drops without a cancellation survey. This cluster covers detection and recovery."
    },
    {
      "slug": "funnel-profit-leaks",
      "title": "Funnel & Profit Leaks",
      "description": "Identify profit leaks across your customer journey — conversion gaps, response delays, and funnel stages that bleed margin.",
      "published": "2026-07-16",
      "postSlugs": [
        "identify-profit-leaks",
        "funnel-conversion-leaks",
        "cart-abandonment-revenue-leak",
        "agency-proposal-leakage"
      ],
      "keywords": [
        "profit leaks",
        "identify profit leaks",
        "funnel leakage",
        "conversion leak",
        "revenue leak identification"
      ],
      "faq": [
        {
          "q": "What is a profit leak?",
          "a": "A profit leak is revenue you almost captured but lost due to a broken funnel stage — slow response, weak conversion, or customers who never buy again."
        },
        {
          "q": "Where should I look first for funnel leaks?",
          "a": "Measure conversion between each step (visit → lead → sale → repeat). The largest gap vs benchmark is usually your highest-impact leak."
        }
      ],
      "intro": "Profit leaks hide between funnel stages. These articles show how to find them with rough math and benchmarks — no finance team required."
    },
    {
      "slug": "revenue-leakage",
      "title": "Revenue Leakage",
      "description": "Everything about finding, measuring, and fixing revenue leakage — definitions, examples, detection methods, and recovery playbooks.",
      "published": "2026-07-16",
      "postSlugs": [
        "what-is-revenue-leakage",
        "revenue-leakage-meaning",
        "revenue-leakage-examples",
        "revenue-leakage-detection",
        "revenue-leakage-analysis",
        "saas-revenue-leakage"
      ],
      "keywords": [
        "revenue leakage",
        "revenue leak",
        "revenue leakage meaning",
        "revenue leakage examples",
        "revenue leakage detection"
      ],
      "faq": [
        {
          "q": "What is revenue leakage?",
          "a": "Revenue leakage is money your business should earn but does not — because of gaps in acquisition, conversion, retention, billing, or expansion — not because demand disappeared."
        },
        {
          "q": "How much revenue do businesses typically leak?",
          "a": "Estimates vary by model; many B2B and subscription businesses see single-digit percentages of revenue at risk from billing errors, churn, and funnel gaps. Directional diagnostics help prioritize fixes."
        },
        {
          "q": "Is revenue leakage the same as churn?",
          "a": "No. Churn is one source. Leakage also includes failed payments, slow follow-up, cart abandonment, unbilled usage, and missing upsells — often before a customer ever leaves."
        }
      ],
      "intro": "Revenue leakage is the gap between what your funnel could produce and what you actually collect. This cluster covers definitions, real-world examples, and how to detect leaks before they compound."
    }
  ],
  "posts": [
    {
      "slug": "revenue-leakage-examples",
      "title": "12 Revenue Leakage Examples (SaaS, Ecommerce, Agency & Service)",
      "description": "Concrete revenue leakage examples with estimated impact — trial conversion, cart abandonment, proposal ghosting, failed payments, and more.",
      "published": "2026-07-16",
      "pillar": "revenue-leakage",
      "keywords": [
        "revenue leakage examples",
        "examples of revenue leakage",
        "revenue leak examples"
      ],
      "relatedSlugs": [
        "what-is-revenue-leakage",
        "saas-revenue-leakage",
        "cart-abandonment-revenue-leak"
      ],
      "faq": [
        {
          "q": "What is an example of revenue leakage?",
          "a": "A SaaS company with 500 trials/month converting at 4% instead of 12% — at $150 ARPU that is thousands per month left uncaptured."
        },
        {
          "q": "What is the most common revenue leak?",
          "a": "It varies by model: SaaS often leaks in conversion and billing; ecommerce in cart abandonment; agencies in follow-up and scope creep."
        }
      ],
      "blocks": [
        {
          "type": "p",
          "text": "These revenue leakage examples are patterns we see across niches — often two or three active at once. Use them to spot what sounds familiar, then quantify with your own numbers."
        },
        {
          "type": "h2",
          "text": "SaaS examples"
        },
        {
          "type": "ul",
          "items": [
            "Trial-to-paid below benchmark with healthy top-of-funnel",
            "8% monthly churn with no exit survey or save offer",
            "Failed card charges with no dunning sequence",
            "Single-plan customers never shown upgrade path"
          ]
        },
        {
          "type": "p",
          "text": "Deep dive: [SaaS revenue leakage](/blog/saas-revenue-leakage) · [SaaS diagnostic](/for/saas)"
        },
        {
          "type": "h2",
          "text": "Ecommerce examples"
        },
        {
          "type": "ul",
          "items": [
            "70%+ cart abandonment without recovery emails",
            "One-time buyers with no second-purchase campaign",
            "Refund spikes on best-selling SKUs"
          ]
        },
        {
          "type": "p",
          "text": "Related: [cart abandonment revenue leak](/blog/cart-abandonment-revenue-leak)"
        },
        {
          "type": "h2",
          "text": "Agency & service examples"
        },
        {
          "type": "ul",
          "items": [
            "Proposals sent, never followed up within 48 hours",
            "No-show appointments without reminders or deposits",
            "Invoices sent weeks after work completed"
          ]
        },
        {
          "type": "p",
          "text": "Related: [agency proposal leakage](/blog/agency-proposal-leakage)"
        },
        {
          "type": "cta",
          "headline": "Which examples match your business?",
          "subline": "Rank your top 3 leaks by estimated monthly impact",
          "href": "/?fresh=1#start"
        }
      ]
    },
    {
      "slug": "agency-proposal-leakage",
      "title": "Agency Proposal Leakage: When Pipeline Dies After the Send",
      "description": "Agency revenue leakage from proposal ghosting, slow follow-up, scope creep, and no-show discovery calls — with recovery tactics.",
      "published": "2026-07-16",
      "pillar": "funnel-profit-leaks",
      "keywords": [
        "agency proposal leakage",
        "agency revenue leak",
        "proposal follow up revenue"
      ],
      "relatedSlugs": [
        "funnel-conversion-leaks",
        "identify-profit-leaks",
        "revenue-leakage-examples"
      ],
      "faq": [
        {
          "q": "Why do agency proposals leak revenue?",
          "a": "Proposals sent without timed follow-up, unclear next steps, or pricing that does not match the buyer's decision process."
        },
        {
          "q": "When should you follow up on a proposal?",
          "a": "Within 24–48 hours of sending, then on a short cadence (day 3, 7, 14) with a specific ask — not 'just checking in.'"
        }
      ],
      "blocks": [
        {
          "type": "p",
          "text": "Agency proposal leakage is revenue you already earned in effort — discovery done, proposal crafted — but never closed because the post-send process failed."
        },
        {
          "type": "h2",
          "text": "Leak patterns for agencies & services"
        },
        {
          "type": "ul",
          "items": [
            "Proposal sent Friday, no touch until next week",
            "No deposit or calendar hold before scoping work",
            "Scope creep on fixed-price deals",
            "Invoices net-30 while payroll is weekly",
            "No-show calls without SMS reminders"
          ]
        },
        {
          "type": "p",
          "text": "Broader funnel view: [funnel conversion leaks](/blog/funnel-conversion-leaks). [Agency diagnostic](/for/agency?fresh=1#start)."
        },
        {
          "type": "cta",
          "headline": "Score your agency funnel leaks",
          "href": "/for/agency?fresh=1#start"
        }
      ]
    },
    {
      "slug": "cart-abandonment-revenue-leak",
      "title": "Cart Abandonment Revenue Leak: Recover Lost Ecommerce Sales",
      "description": "How cart abandonment creates revenue leakage — benchmarks, recovery emails, checkout fixes, and dollar impact estimates.",
      "published": "2026-07-16",
      "pillar": "funnel-profit-leaks",
      "keywords": [
        "cart abandonment revenue leak",
        "cart abandonment revenue loss",
        "ecommerce revenue leakage"
      ],
      "relatedSlugs": [
        "funnel-conversion-leaks",
        "revenue-leakage-examples",
        "revenue-leakage-detection"
      ],
      "faq": [
        {
          "q": "How much revenue is lost to cart abandonment?",
          "a": "Industry averages often cite 60–80% abandonment. On $50k monthly GMV, recovering even 5% of abandoned carts can mean thousands per month."
        },
        {
          "q": "What reduces cart abandonment fastest?",
          "a": "Guest checkout, transparent shipping costs early, trust badges, and a 3-email recovery sequence within 72 hours."
        }
      ],
      "blocks": [
        {
          "type": "p",
          "text": "Cart abandonment is one of the clearest revenue leaks in ecommerce: intent was real, payment did not happen. The fix is usually recovery plus checkout friction — not more traffic."
        },
        {
          "type": "h2",
          "text": "Common abandonment causes"
        },
        {
          "type": "ul",
          "items": [
            "Shipping or tax surprise at checkout",
            "Forced account creation",
            "Slow mobile checkout",
            "No abandoned-cart email sequence",
            "Stock or variant confusion on PDP"
          ]
        },
        {
          "type": "p",
          "text": "See more patterns in [revenue leakage examples](/blog/revenue-leakage-examples). Run the [ecommerce diagnostic](/for/ecommerce?fresh=1#start)."
        },
        {
          "type": "cta",
          "headline": "Quantify your cart and retention leaks",
          "href": "/for/ecommerce?fresh=1#start"
        }
      ]
    },
    {
      "slug": "failed-payment-recovery",
      "title": "Failed Payment Recovery: Stop Involuntary Churn Revenue Leaks",
      "description": "Recover revenue from failed card charges — dunning emails, Smart Retries, card updater, and benchmarks for subscription businesses.",
      "published": "2026-07-16",
      "pillar": "billing-recovery",
      "keywords": [
        "failed payment recovery",
        "dunning emails",
        "involuntary churn",
        "recover failed payments"
      ],
      "relatedSlugs": [
        "subscription-billing-leaks",
        "saas-revenue-leakage",
        "revenue-leakage-examples"
      ],
      "faq": [
        {
          "q": "What is failed payment recovery?",
          "a": "Automated retries and customer communication to collect revenue when a subscription charge fails — before the customer churns involuntarily."
        },
        {
          "q": "How much revenue can dunning recover?",
          "a": "Many SaaS businesses recover 20–40% of failed charges with proper retries and emails; results vary by audience and card mix."
        }
      ],
      "blocks": [
        {
          "type": "p",
          "text": "Failed payment recovery targets involuntary churn — customers who did not intend to leave. Without dunning, you leak MRR that a few emails and retries would save."
        },
        {
          "type": "h2",
          "text": "Recovery stack"
        },
        {
          "type": "ol",
          "items": [
            "Enable processor Smart Retries (e.g. Stripe Billing)",
            "Send branded dunning emails at day 0, 3, and 7",
            "Link to a hosted update-payment page",
            "Surface failed payments in a weekly ops review",
            "Track recovery rate and revenue recaptured"
          ]
        },
        {
          "type": "p",
          "text": "Related: [subscription billing leaks](/blog/subscription-billing-leaks) · [SaaS revenue leakage](/blog/saas-revenue-leakage)"
        },
        {
          "type": "cta",
          "headline": "Include billing leaks in your diagnostic",
          "href": "/for/saas?fresh=1#start"
        }
      ]
    },
    {
      "slug": "funnel-conversion-leaks",
      "title": "Funnel Conversion Leaks: Where Visitors Become Lost Revenue",
      "description": "Find funnel conversion leaks at each stage — awareness, interest, decision, action — with benchmarks and fix patterns.",
      "published": "2026-07-16",
      "pillar": "funnel-profit-leaks",
      "keywords": [
        "funnel conversion leaks",
        "conversion funnel leaks",
        "sales funnel revenue leak"
      ],
      "relatedSlugs": [
        "cart-abandonment-revenue-leak",
        "revenue-leakage-detection",
        "identify-profit-leaks"
      ],
      "faq": [
        {
          "q": "What causes funnel conversion leaks?",
          "a": "Friction, slow response, unclear value prop, trust gaps, and missing recovery flows at each transition."
        },
        {
          "q": "Which funnel stage leaks the most?",
          "a": "Depends on business: B2B often leaks at demo-to-close; ecommerce at cart-to-purchase; SaaS at trial-to-paid."
        }
      ],
      "blocks": [
        {
          "type": "p",
          "text": "Funnel conversion leaks are drop-offs between stages that should connect. You do not need perfect analytics — compare each transition to a benchmark and estimate dollars left on the table."
        },
        {
          "type": "h2",
          "text": "Stage-by-stage leaks"
        },
        {
          "type": "ul",
          "items": [
            "Awareness → interest: wrong audience or weak hook",
            "Interest → intent: no clear next step or social proof",
            "Intent → purchase: checkout friction, pricing shock",
            "Purchase → repeat: no onboarding to second order"
          ]
        },
        {
          "type": "p",
          "text": "Ecommerce-specific: [cart abandonment revenue leak](/blog/cart-abandonment-revenue-leak). Agency-specific: [proposal leakage](/blog/agency-proposal-leakage)."
        },
        {
          "type": "cta",
          "headline": "Map your funnel and score each stage",
          "href": "/?fresh=1#start"
        }
      ]
    },
    {
      "slug": "identify-profit-leaks",
      "title": "How to Identify Profit Leaks in Your Business (Not Just Revenue)",
      "description": "Identify profit leaks by connecting funnel gaps to margin — discount creep, scope creep, CAC waste, and recovery opportunities.",
      "published": "2026-07-16",
      "pillar": "funnel-profit-leaks",
      "keywords": [
        "identify profit leaks",
        "profit leak identification",
        "profit leaks in business"
      ],
      "relatedSlugs": [
        "revenue-leakage-detection",
        "funnel-conversion-leaks",
        "revenue-leakage-analysis"
      ],
      "faq": [
        {
          "q": "What is a profit leak?",
          "a": "Revenue you lose or margin you give away through operational gaps — not just top-line shortfalls."
        },
        {
          "q": "How is a profit leak different from revenue leakage?",
          "a": "Revenue leakage focuses on uncaptured sales. Profit leaks include margin erosion: discounts, refunds, unpaid scope, and inefficient acquisition."
        }
      ],
      "blocks": [
        {
          "type": "p",
          "text": "To identify profit leaks, follow dollars past the sale. A lead that never converts wastes CAC. A client who gets free scope erodes margin. A failed renewal kills LTV. Same funnel, different accounting lens."
        },
        {
          "type": "h2",
          "text": "Profit leak checklist"
        },
        {
          "type": "ul",
          "items": [
            "Discounts that never expire or auto-renew at promo rates",
            "Refund rate spikes on specific products or cohorts",
            "Sales cycle length growing while close rate falls",
            "Support load from customers who never activated",
            "Invoices paid late — cash timing hurts runway"
          ]
        },
        {
          "type": "p",
          "text": "Measure funnel leaks first with [revenue leakage detection](/blog/revenue-leakage-detection), then layer unit economics."
        },
        {
          "type": "cta",
          "headline": "Rank leaks by estimated monthly impact",
          "href": "/?fresh=1#start"
        }
      ]
    },
    {
      "slug": "revenue-leakage-analysis",
      "title": "Revenue Leakage Analysis: Framework for Prioritizing Fixes",
      "description": "A six-category revenue leakage analysis framework — acquisition, response, conversion, retention, billing, expansion — with prioritization matrix.",
      "published": "2026-07-16",
      "pillar": "revenue-leakage",
      "keywords": [
        "revenue leakage analysis",
        "revenue leak analysis",
        "revenue leakage framework"
      ],
      "relatedSlugs": [
        "revenue-leakage-detection",
        "identify-profit-leaks",
        "revenue-leakage-meaning"
      ],
      "faq": [
        {
          "q": "What is revenue leakage analysis?",
          "a": "A structured review of where money is lost across your customer journey, with dollar estimates so you fix high-impact leaks first."
        },
        {
          "q": "How often should you run leakage analysis?",
          "a": "Quarterly for most SMBs, or after major funnel changes (new pricing, checkout, sales process)."
        }
      ],
      "blocks": [
        {
          "type": "p",
          "text": "Revenue leakage analysis turns vague frustration (“we should be doing better”) into a ranked backlog. Score each category 1–5 for severity, then multiply by estimated monthly dollars at risk."
        },
        {
          "type": "h2",
          "text": "Six leak categories"
        },
        {
          "type": "ul",
          "items": [
            "Acquisition — wrong traffic, weak positioning",
            "Response — slow or missing follow-up",
            "Conversion — trials, demos, carts that stall",
            "Retention — churn and failed activation",
            "Billing — failed payments and invoice delays",
            "Expansion — missed upsells and annual plans"
          ]
        },
        {
          "type": "h2",
          "text": "Prioritization matrix"
        },
        {
          "type": "p",
          "text": "Plot each leak on impact (monthly $) vs effort (time to fix). Quick wins in the high-impact / low-effort quadrant go first — often response time, dunning emails, or cart recovery."
        },
        {
          "type": "p",
          "text": "Pair with [revenue leakage detection](/blog/revenue-leakage-detection) for measurement steps."
        },
        {
          "type": "cta",
          "headline": "Get a scored leakage report for your business",
          "href": "/?fresh=1#start"
        }
      ]
    },
    {
      "slug": "revenue-leakage-detection",
      "title": "Revenue Leakage Detection: 5-Step Process to Find Hidden Losses",
      "description": "How to detect revenue leakage with benchmarks, funnel mapping, and dollar estimates — without a full analytics stack.",
      "published": "2026-07-16",
      "pillar": "revenue-leakage",
      "keywords": [
        "revenue leakage detection",
        "detect revenue leaks",
        "revenue leak identification strategies"
      ],
      "relatedSlugs": [
        "identify-profit-leaks",
        "revenue-leakage-analysis",
        "what-is-revenue-leakage"
      ],
      "faq": [
        {
          "q": "How do you detect revenue leakage?",
          "a": "Map your funnel end to end, measure conversion at each step, compare to benchmarks, estimate monthly dollar impact, and fix the highest-impact stage first."
        },
        {
          "q": "What tools detect revenue leakage?",
          "a": "Stripe, your CRM, and analytics cover most gaps. Structure matters more than tooling — a diagnostic questionnaire can surface leaks in minutes."
        }
      ],
      "blocks": [
        {
          "type": "p",
          "text": "Revenue leakage detection is not about more dashboards. It is about asking: where does the funnel drop below benchmark, and what does that gap cost per month?"
        },
        {
          "type": "h2",
          "text": "Five-step detection process"
        },
        {
          "type": "ol",
          "items": [
            "Draw the journey from stranger to repeat buyer — one owner per stage",
            "Attach a metric to each transition (even rough ranges)",
            "Color-code stages red/yellow/green vs niche benchmarks",
            "Multiply lost conversions by average revenue per customer",
            "Rank leaks by impact and effort; assign one owner per fix"
          ]
        },
        {
          "type": "p",
          "text": "For profit-focused framing, see [how to identify profit leaks](/blog/identify-profit-leaks). For billing-specific leaks, see [failed payment recovery](/blog/failed-payment-recovery)."
        },
        {
          "type": "h2",
          "text": "Signals leakage is happening"
        },
        {
          "type": "ul",
          "items": [
            "Traffic or leads up, revenue flat",
            "CAC rising without LTV improvement",
            "Strong pipeline, weak close rate",
            "Impressions up in search, clicks flat (intent mismatch)"
          ]
        },
        {
          "type": "cta",
          "headline": "Run automated leakage detection in 5 minutes",
          "href": "/?fresh=1#start"
        }
      ]
    },
    {
      "slug": "revenue-leakage-meaning",
      "title": "Revenue Leakage Meaning: What People Actually Mean (and Confuse)",
      "description": "Revenue leakage meaning vs churn, shrinkage, and margin erosion — plain-language definitions for founders and operators.",
      "published": "2026-07-16",
      "pillar": "revenue-leakage",
      "keywords": [
        "revenue leakage meaning",
        "revenue leak meaning",
        "revenue leakage synonyms"
      ],
      "relatedSlugs": [
        "what-is-revenue-leakage",
        "revenue-leakage-analysis",
        "identify-profit-leaks"
      ],
      "faq": [
        {
          "q": "What does revenue leakage mean?",
          "a": "It means earned or almost-earned revenue is lost due to process failures — billing, funnel, or operations — rather than lack of market demand."
        },
        {
          "q": "Is revenue leakage the same as revenue shrinkage?",
          "a": "Shrinkage often refers to inventory or retail loss. Revenue leakage usually describes funnel and billing gaps in digital and service businesses."
        }
      ],
      "blocks": [
        {
          "type": "p",
          "text": "When people search revenue leakage meaning, they usually want a plain definition — not a finance textbook. Here it is: leakage is money slipping out of your business because a step in the journey failed, not because the market vanished."
        },
        {
          "type": "h2",
          "text": "Terms people confuse with revenue leakage"
        },
        {
          "type": "ul",
          "items": [
            "Churn: customers who leave — one source of leakage, not the whole picture",
            "Margin erosion: often caused by discounts that never expire or scope creep",
            "Leakage vs attrition: attrition is loss of customers; leakage includes never converting them at all",
            "Revenue recognition errors: accounting timing — related but not identical"
          ]
        },
        {
          "type": "p",
          "text": "For a full framework across six leak categories, read [revenue leakage analysis](/blog/revenue-leakage-analysis)."
        },
        {
          "type": "cta",
          "headline": "See what leakage looks like for your business type",
          "href": "/?fresh=1#start"
        }
      ]
    },
    {
      "slug": "saas-revenue-leakage",
      "title": "SaaS Revenue Leakage: Trial, Churn & Billing Leaks Explained",
      "description": "Where SaaS companies leak revenue — trial conversion, activation, churn, failed payments, and expansion — with benchmarks and fixes.",
      "published": "2026-07-16",
      "pillar": "revenue-leakage",
      "keywords": [
        "saas revenue leakage",
        "saas revenue leak",
        "subscription revenue leakage"
      ],
      "relatedSlugs": [
        "subscription-billing-leaks",
        "failed-payment-recovery",
        "revenue-leakage-examples"
      ],
      "faq": [
        {
          "q": "Where do SaaS companies leak the most revenue?",
          "a": "Typically trial-to-paid conversion, early churn before activation, and involuntary churn from failed card charges."
        },
        {
          "q": "What is a good SaaS trial conversion rate?",
          "a": "Varies by model; self-serve often targets 10–25% trial-to-paid. Below 5% with healthy signups usually signals a leak."
        }
      ],
      "blocks": [
        {
          "type": "p",
          "text": "SaaS revenue leakage rarely shows up as one broken metric. It is usually a stack: trials that never activate, cards that fail silently, and customers who would upgrade but never see the right plan."
        },
        {
          "type": "h2",
          "text": "Top SaaS leak points"
        },
        {
          "type": "ul",
          "items": [
            "Trial signup without onboarding to first value",
            "Pricing page mismatch vs actual buyer persona",
            "Monthly churn above 5–7% without save flows",
            "Failed payments with no Smart Retries or dunning",
            "Annual plans under-promoted vs monthly"
          ]
        },
        {
          "type": "p",
          "text": "Billing deep dive: [subscription billing leaks](/blog/subscription-billing-leaks) and [failed payment recovery](/blog/failed-payment-recovery)."
        },
        {
          "type": "p",
          "text": "Run the [SaaS revenue leak diagnostic](/for/saas) with pre-filled benchmarks."
        },
        {
          "type": "cta",
          "headline": "SaaS founders: find your top 3 leaks",
          "href": "/for/saas?fresh=1#start"
        }
      ]
    },
    {
      "slug": "subscription-billing-leaks",
      "title": "Subscription Billing Leaks: Pricing, Dunning & Renewal Gaps",
      "description": "Subscription billing leaks beyond failed payments — annual plan gaps, proration errors, trial billing surprises, and leakage math.",
      "published": "2026-07-16",
      "pillar": "billing-recovery",
      "keywords": [
        "subscription billing leaks",
        "billing revenue leakage",
        "subscription revenue recovery"
      ],
      "relatedSlugs": [
        "failed-payment-recovery",
        "saas-revenue-leakage",
        "revenue-leakage-analysis"
      ],
      "faq": [
        {
          "q": "What are subscription billing leaks?",
          "a": "Revenue lost in the billing layer: failed charges, wrong plan assignments, missing annual upsells, and customers on legacy pricing."
        },
        {
          "q": "How do I audit subscription billing?",
          "a": "Export active subs, segment by plan and tenure, check failed payment rate, and compare MRR to expected from list price."
        }
      ],
      "blocks": [
        {
          "type": "p",
          "text": "Subscription billing leaks sit between product and finance. Customers stay subscribed but pay less than they should, or churn silently when cards fail."
        },
        {
          "type": "h2",
          "text": "Billing leak types"
        },
        {
          "type": "ul",
          "items": [
            "Involuntary churn from failed payments",
            "Grandfathered pricing never migrated",
            "Trials that convert to wrong plan tier",
            "No annual discount — monthly bleed",
            "Tax or currency misconfiguration on invoices"
          ]
        },
        {
          "type": "p",
          "text": "Fix failed charges first: [failed payment recovery](/blog/failed-payment-recovery)."
        },
        {
          "type": "cta",
          "headline": "Score billing + funnel leaks together",
          "href": "/for/saas?fresh=1#start"
        }
      ]
    },
    {
      "slug": "what-is-revenue-leakage",
      "title": "What Is Revenue Leakage? Definition, Causes & How to Fix It",
      "description": "Revenue leakage explained: what it means, common causes across SaaS and ecommerce, and how to find leaks before they compound.",
      "published": "2026-07-16",
      "pillar": "revenue-leakage",
      "keywords": [
        "what is revenue leakage",
        "revenue leakage definition",
        "revenue leak meaning"
      ],
      "relatedSlugs": [
        "revenue-leakage-meaning",
        "revenue-leakage-examples",
        "revenue-leakage-detection"
      ],
      "faq": [
        {
          "q": "What is revenue leakage in simple terms?",
          "a": "Money you should have earned but did not — because something in your funnel (traffic, sales, billing, retention) failed, not because customers disappeared."
        },
        {
          "q": "Is revenue leakage illegal or fraud?",
          "a": "Usually no. It is operational — slow follow-up, failed payments, cart abandonment, pricing errors — not theft."
        },
        {
          "q": "How is revenue leakage different from low revenue?",
          "a": "Low revenue can mean weak demand. Leakage means demand or customers exist, but process gaps prevent you from capturing full value."
        }
      ],
      "blocks": [
        {
          "type": "p",
          "text": "Revenue leakage is the gap between revenue you could collect and revenue you actually collect. The customer may still be interested, the product may still deliver value, but a broken step — slow demo follow-up, a declined card, an abandoned cart — lets money escape."
        },
        {
          "type": "h2",
          "text": "Common causes of revenue leakage"
        },
        {
          "type": "ul",
          "items": [
            "Acquisition: traffic that never becomes a qualified lead",
            "Response: leads that go cold before anyone replies",
            "Conversion: trials, demos, or carts that stall before payment",
            "Retention: customers who churn early or never activate",
            "Billing: failed payments, invoice delays, pricing drift",
            "Expansion: customers who would upgrade but never see an offer"
          ]
        },
        {
          "type": "p",
          "text": "See [revenue leakage examples](/blog/revenue-leakage-examples) for worked patterns by business type."
        },
        {
          "type": "h2",
          "text": "How to find revenue leakage"
        },
        {
          "type": "p",
          "text": "Map your funnel, measure conversion between steps, benchmark each rate, and estimate dollar impact. Our [revenue leakage detection](/blog/revenue-leakage-detection) guide walks through the process step by step."
        },
        {
          "type": "cta",
          "headline": "Find your top 3 revenue leaks in 5 minutes",
          "subline": "Free directional diagnostic — no spreadsheet required",
          "href": "/?fresh=1#start"
        }
      ]
    }
  ],
  "generatedAt": "2026-07-16T14:48:38.806Z"
} as const;
