import Link from "next/link";
import { LegalPage } from "@/components/LegalPage";
import { REPORT_PRICE_LABEL } from "@/lib/preview";
import { getContactEmail, SITE_NAME } from "@/lib/site";

export const metadata = {
  title: "Terms of Service",
  description: `Terms for using ${SITE_NAME}.`,
  alternates: {
    canonical: "/terms",
  },
};

export default function TermsPage() {
  const contactEmail = getContactEmail();

  return (
    <LegalPage title="Terms of Service">
      <p>
        By using {SITE_NAME} (&quot;the service&quot;), you agree to these terms. If you do
        not agree, please do not use the site.
      </p>

      <h2>What the service is</h2>
      <p>
        {SITE_NAME} is an online questionnaire that estimates where a business may be
        losing revenue, based on your answers. You can complete a free preview. You may pay a
        one-time fee (currently {REPORT_PRICE_LABEL}) to unlock a fuller written report with
        category breakdowns and recommendations.
      </p>

      <h2>Not professional advice</h2>
      <p>
        The diagnostic, scores, dollar estimates, and recommendations are{" "}
        <strong>informational only</strong>. They are generated by rules and formulas applied to
        your answers — not by a human consultant reviewing your books. They are{" "}
        <strong>not</strong> financial, accounting, tax, or legal advice. Do not make major
        business decisions based only on this report. Talk to qualified professionals for advice
        specific to your situation.
      </p>

      <h2>Estimates are approximate</h2>
      <p>
        Revenue loss figures are directional estimates. They depend on the accuracy of your
        answers, assumptions built into our models, and simplified math. Actual results will vary.
        We do not guarantee that fixing any issue will recover any particular amount of revenue.
      </p>

      <h2>Your answers</h2>
      <p>
        You are responsible for providing answers that are as accurate as you can make them.
        Guesses, ranges, and &quot;not sure&quot; responses are allowed, but they affect the
        output.
      </p>

      <h2>Free preview vs paid report</h2>
      <ul>
        <li>The preview shows a banded total loss estimate and highlights your top leak category.</li>
        <li>Per-category dollar amounts and the full fix-it report are unlocked after payment.</li>
        <li>We may change questionnaire content, scoring, or pricing over time.</li>
      </ul>

      <h2>Payment</h2>
      <p>
        Paid reports are sold as a <strong>one-time purchase</strong> (currently{" "}
        {REPORT_PRICE_LABEL}). Checkout is handled by Stripe. By paying, you also agree to
        Stripe&apos;s terms where applicable. Prices may change for future purchases; the price
        shown at checkout is what you pay.
      </p>

      <h2>Refunds</h2>
      <p>
        We offer a <strong>7-day money-back guarantee</strong> on the paid report. If you are
        unhappy with your purchase, contact us within 7 days of payment and we will refund you.
        We may ask for your email or payment details to locate the transaction. After a refund,
        access to the paid report may be revoked.
      </p>

      <h2>Report access</h2>
      <p>
        After purchase, you can view your report on the site and may receive an email with a
        link. Links include an access token and can stop working after a period of time or if we
        delete the underlying record. Save or print your report if you need a long-term copy.
      </p>

      <h2>Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the service for anything unlawful.</li>
        <li>Try to access other people&apos;s diagnostics without authorization.</li>
        <li>Overload, scrape, or reverse-engineer the service in abusive ways.</li>
      </ul>

      <h2>Disclaimer of warranties</h2>
      <p>
        The service is provided <strong>&quot;as is&quot;</strong> and <strong>&quot;as available&quot;</strong>
        without warranties of any kind, express or implied, including fitness for a particular
        purpose or accuracy of results.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, we are not liable for any indirect, incidental,
        special, or consequential damages, or for lost profits or revenue, arising from your use
        of the service. Our total liability for any claim related to the service is limited to the
        amount you paid us for the report in the 12 months before the claim (or {REPORT_PRICE_LABEL}{" "}
        if you only used the free preview).
      </p>

      <h2>Changes to the service or terms</h2>
      <p>
        We may update the site, diagnostic, or these terms. Material changes will be reflected by
        updating the date at the top of this page. Continued use after changes means you accept the
        updated terms.
      </p>

      <h2>Contact</h2>
      {contactEmail ? (
        <p>
          Questions about these terms or refund requests:{" "}
          <a href={`mailto:${contactEmail}`}>{contactEmail}</a>
        </p>
      ) : (
        <p>
          Questions about these terms or refund requests: reply to any email you received from us
          about your report, or contact the site operator using the email configured for report
          delivery.
        </p>
      )}

      <p className="text-sm text-slate-600">
        See also our <Link href="/privacy">Privacy Policy</Link>.
      </p>
    </LegalPage>
  );
}
