/**
 * Reads content/blog JSON files and emits lib/blog/manifest.ts for Next.js.
 * Run: node scripts/generate-blog.mjs
 */
import { readdir, readFile, writeFile } from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const contentDir = path.join(root, "content", "blog");
const outFile = path.join(root, "lib", "blog", "manifest.ts");

async function readJson(filePath) {
  const raw = await readFile(filePath, "utf8");
  return JSON.parse(raw);
}

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

async function main() {
  const author = await readJson(path.join(contentDir, "author.json"));

  const pillarDir = path.join(contentDir, "pillars");
  const pillarFiles = (await readdir(pillarDir)).filter((f) => f.endsWith(".json"));
  const pillars = await Promise.all(
    pillarFiles.map((f) => readJson(path.join(pillarDir, f)))
  );

  const postsDir = path.join(contentDir, "posts");
  const postFiles = (await readdir(postsDir)).filter((f) => f.endsWith(".json"));
  const posts = await Promise.all(
    postFiles.map((f) => readJson(path.join(postsDir, f)))
  );

  const pillarSlugs = new Set(pillars.map((p) => p.slug));
  const postSlugs = new Set(posts.map((p) => p.slug));

  for (const pillar of pillars) {
    assert(pillar.slug && pillar.title, `Pillar missing slug/title: ${pillar.slug}`);
    for (const slug of pillar.postSlugs) {
      assert(postSlugs.has(slug), `Pillar "${pillar.slug}" references unknown post "${slug}"`);
    }
  }

  for (const post of posts) {
    assert(post.slug && post.title, `Post missing slug/title`);
    assert(
      pillarSlugs.has(post.pillar),
      `Post "${post.slug}" references unknown pillar "${post.pillar}"`
    );
    for (const related of post.relatedSlugs ?? []) {
      assert(
        postSlugs.has(related),
        `Post "${post.slug}" references unknown related post "${related}"`
      );
      assert(related !== post.slug, `Post "${post.slug}" cannot relate to itself`);
    }
  }

  const manifest = {
    author,
    pillars: pillars.sort((a, b) => a.title.localeCompare(b.title)),
    posts: posts.sort((a, b) => b.published.localeCompare(a.published) || a.title.localeCompare(b.title)),
    generatedAt: new Date().toISOString(),
  };

  const ts = `// AUTO-GENERATED by scripts/generate-blog.mjs — do not edit by hand.
import type { BlogManifest } from "./types";

export const blogManifest: BlogManifest = ${JSON.stringify(manifest, null, 2)} as const;
`;

  await writeFile(outFile, ts, "utf8");
  console.log(
    `[generate-blog] Wrote ${outFile} (${pillars.length} pillars, ${posts.length} posts)`
  );
}

main().catch((err) => {
  console.error("[generate-blog]", err.message);
  process.exit(1);
});
