import type { Question } from "../types";
import { cw, higherIsWorse, lowerIsWorse } from "./helpers";
import { withNotSure } from "./shared";

export const agencyQuestions: Question[] = [
  {
    id: "biggest_frustration",
    label: "What's your single biggest growth frustration right now?",
    type: "select",
    qualitative: true,
    options: [
      { value: "getting_leads", label: "Not enough inbound leads", riskScore: 0 },
      { value: "closing_deals", label: "Proposals don't close", riskScore: 0 },
      { value: "client_retention", label: "Clients don't stay or expand", riskScore: 0 },
      { value: "slow_response", label: "Too slow to respond to leads", riskScore: 0 },
      { value: "not_sure", label: "Not sure — show me everything", riskScore: 0 },
    ],
    categoryWeights: [],
  },
  {
    id: "monthly_leads",
    label: "Monthly inbound leads",
    type: "band",
    bands: [
      { value: "under_10", label: "Under 10", midpoint: 5 },
      { value: "10_40", label: "10 – 40", midpoint: 25 },
      { value: "40_100", label: "40 – 100", midpoint: 60 },
      { value: "100_plus", label: "100+", midpoint: 150 },
    ],
    categoryWeights: [],
  },
  {
    id: "response_time",
    label: "Average time-to-first-response to new leads",
    type: "select",
    options: [
      { value: "under_1h", label: "Under 1 hour", riskScore: 10 },
      { value: "1_4h", label: "1–4 hours", riskScore: 35 },
      { value: "4_24h", label: "4–24 hours", riskScore: 65 },
      { value: "over_24h", label: "Over 24 hours", riskScore: 95 },
    ],
    categoryWeights: [cw("response", 1)],
  },
  withNotSure({
    id: "discovery_booking_rate",
    label: "Discovery call booking rate (%)",
    helpText: "% of leads that book a discovery call.",
    benchmark: "Strong agencies: 35–50%",
    type: "percent",
    min: 0,
    max: 100,
    placeholder: "e.g. 30",
    scoreNumeric: (v) => lowerIsWorse(v, 45, 15),
    categoryWeights: [cw("conversion", 0.7), cw("response", 0.3)],
  }),
  withNotSure({
    id: "proposal_send_rate",
    label: "Proposal send rate (%)",
    helpText: "% of qualified discovery calls that receive a proposal.",
    benchmark: "Typical: 60–80%",
    type: "percent",
    min: 0,
    max: 100,
    placeholder: "e.g. 70",
    scoreNumeric: (v) => lowerIsWorse(v, 70, 20),
    categoryWeights: [cw("conversion", 0.8), cw("response", 0.2)],
  }),
  withNotSure({
    id: "proposal_close_rate",
    label: "Proposal close rate (%)",
    benchmark: "Typical: 25–40%",
    type: "percent",
    min: 0,
    max: 100,
    placeholder: "e.g. 25",
    scoreNumeric: (v) => lowerIsWorse(v, 40, 15),
    categoryWeights: [cw("conversion", 1)],
  }),
  {
    id: "avg_client_value",
    label: "Average client value (initial project)",
    type: "band",
    bands: [
      { value: "under_5k", label: "Under $5,000", midpoint: 3000 },
      { value: "5k_15k", label: "$5,000 – $15,000", midpoint: 10000 },
      { value: "15k_50k", label: "$15,000 – $50,000", midpoint: 25000 },
      { value: "50k_plus", label: "$50,000+", midpoint: 75000 },
    ],
    categoryWeights: [],
  },
  {
    id: "client_lifetime",
    label: "Average client lifetime",
    type: "select",
    options: [
      { value: "long", label: "12+ months / 3+ projects", riskScore: 10 },
      { value: "medium", label: "6–12 months / 2 projects", riskScore: 40 },
      { value: "short", label: "Under 6 months / 1 project", riskScore: 85 },
    ],
    categoryWeights: [cw("retention", 1)],
  },
  {
    id: "follow_up_system",
    label: "Structured follow-up system",
    type: "select",
    options: [
      { value: "robust", label: "Robust — automated sequences & CRM tasks", riskScore: 10 },
      { value: "adhoc", label: "Ad-hoc — manual when we remember", riskScore: 55 },
      { value: "none", label: "None", riskScore: 90 },
    ],
    categoryWeights: [cw("response", 0.5), cw("conversion", 0.5)],
  },
  {
    id: "overdue_invoices",
    label: "Do you have overdue client invoices right now?",
    type: "yesno",
    options: [
      { value: "no", label: "No — collections are current", riskScore: 10 },
      { value: "yes", label: "Yes — some clients are behind", riskScore: 80 },
    ],
    categoryWeights: [cw("billing", 1)],
  },
  {
    id: "upsell_frequency",
    label: "Upsell / cross-sell frequency",
    type: "select",
    options: [
      { value: "frequent", label: "Frequent — part of every engagement", riskScore: 10 },
      { value: "occasional", label: "Occasional", riskScore: 45 },
      { value: "rare", label: "Rare or never", riskScore: 90 },
    ],
    categoryWeights: [cw("expansion", 1)],
  },
];
