import type { Question } from "../types";
import { cw, higherIsWorse, lowerIsWorse } from "./helpers";
import { withNotSure } from "./shared";

export const ecommerceQuestions: Question[] = [
  {
    id: "biggest_frustration",
    label: "What's your single biggest growth frustration right now?",
    type: "select",
    qualitative: true,
    options: [
      { value: "getting_traffic", label: "Not enough traffic or add-to-carts", riskScore: 0 },
      { value: "cart_checkout", label: "Carts don't checkout", riskScore: 0 },
      { value: "repeat_customers", label: "Customers don't buy again", riskScore: 0 },
      { value: "average_order", label: "Order values are too low", riskScore: 0 },
      { value: "not_sure", label: "Not sure — show me everything", riskScore: 0 },
    ],
    categoryWeights: [],
  },
  {
    id: "monthly_sessions",
    label: "Monthly store sessions",
    type: "band",
    bands: [
      { value: "under_5k", label: "Under 5,000", midpoint: 2500 },
      { value: "5k_25k", label: "5,000 – 25,000", midpoint: 15000 },
      { value: "25k_100k", label: "25,000 – 100,000", midpoint: 50000 },
      { value: "100k_plus", label: "100,000+", midpoint: 150000 },
    ],
    categoryWeights: [],
  },
  withNotSure({
    id: "add_to_cart_rate",
    label: "Add-to-cart rate (%)",
    helpText: "Sessions that add at least one item to cart.",
    benchmark: "Typical ecommerce: 8–12%",
    type: "percent",
    min: 0,
    max: 100,
    placeholder: "e.g. 8",
    scoreNumeric: (v) => lowerIsWorse(v, 12, 3),
    categoryWeights: [cw("acquisition", 0.4), cw("conversion", 0.6)],
  }),
  withNotSure({
    id: "checkout_completion_rate",
    label: "Checkout completion rate (%)",
    helpText: "Carts that complete purchase.",
    benchmark: "Typical: 50–65%",
    type: "percent",
    min: 0,
    max: 100,
    placeholder: "e.g. 45",
    scoreNumeric: (v) => lowerIsWorse(v, 65, 25),
    categoryWeights: [cw("conversion", 0.8), cw("billing", 0.2)],
  }),
  {
    id: "average_order_value",
    label: "Average order value",
    type: "band",
    bands: [
      { value: "under_50", label: "Under $50", midpoint: 35 },
      { value: "50_100", label: "$50 – $100", midpoint: 75 },
      { value: "100_200", label: "$100 – $200", midpoint: 140 },
      { value: "200_plus", label: "$200+", midpoint: 300 },
    ],
    categoryWeights: [],
  },
  withNotSure({
    id: "cart_abandonment_rate",
    label: "Cart abandonment rate (%)",
    benchmark: "Typical: 55–75%",
    type: "percent",
    min: 0,
    max: 100,
    placeholder: "e.g. 70",
    scoreNumeric: (v) => higherIsWorse(v, 55, 85),
    categoryWeights: [cw("conversion", 1)],
  }),
  {
    id: "shipping_cost_visibility",
    label: "When do shoppers see shipping costs?",
    type: "select",
    benchmark: "Best practice: show before checkout",
    options: [
      { value: "early", label: "On product or cart page", riskScore: 10 },
      { value: "checkout", label: "At checkout only", riskScore: 55 },
      { value: "late", label: "Final step / surprise at payment", riskScore: 90 },
    ],
    categoryWeights: [cw("conversion", 0.8), cw("acquisition", 0.2)],
  },
  {
    id: "abandoned_cart_emails",
    label: "Do you run abandoned cart emails or SMS?",
    type: "yesno",
    options: [
      { value: "yes", label: "Yes", riskScore: 15 },
      { value: "no", label: "No", riskScore: 80 },
    ],
    categoryWeights: [cw("conversion", 1)],
  },
  withNotSure({
    id: "repeat_purchase_rate",
    label: "Repeat purchase rate within 90 days (%)",
    benchmark: "Strong stores: 25–35%",
    type: "percent",
    min: 0,
    max: 100,
    placeholder: "e.g. 20",
    scoreNumeric: (v) => lowerIsWorse(v, 35, 10),
    categoryWeights: [cw("retention", 1)],
  }),
  withNotSure({
    id: "refund_rate",
    label: "Refund rate (%)",
    helpText: "Share of orders refunded each month.",
    benchmark: "Typical: under 3%",
    type: "percent",
    min: 0,
    max: 100,
    placeholder: "e.g. 4",
    scoreNumeric: (v) => higherIsWorse(v, 3, 12),
    categoryWeights: [cw("billing", 1)],
  }),
  {
    id: "post_purchase_upsell",
    label: "Post-purchase upsell flows",
    type: "select",
    options: [
      { value: "strong", label: "Strong — automated bundles & recommendations", riskScore: 10 },
      { value: "some", label: "Some — occasional offers", riskScore: 45 },
      { value: "none", label: "None", riskScore: 90 },
    ],
    categoryWeights: [cw("expansion", 1)],
  },
];
