import type { Question } from "../types";
import { cw, higherIsWorse, lowerIsWorse } from "./helpers";
import { withNotSure } from "./shared";

export const saasQuestions: Question[] = [
  {
    id: "biggest_frustration",
    label: "What's your single biggest growth frustration right now?",
    type: "select",
    qualitative: true,
    options: [
      { value: "getting_signups", label: "Not enough signups / trials", riskScore: 0 },
      { value: "converting_trials", label: "Trials don't convert to paid", riskScore: 0 },
      { value: "keeping_customers", label: "Customers churn too fast", riskScore: 0 },
      { value: "growing_accounts", label: "Can't grow revenue per account", riskScore: 0 },
      { value: "not_sure", label: "Not sure — show me everything", riskScore: 0 },
    ],
    categoryWeights: [],
  },
  {
    id: "monthly_visitors",
    label: "Monthly website visitors",
    helpText: "Pick the range closest to your traffic.",
    type: "band",
    bands: [
      { value: "under_1k", label: "Under 1,000", midpoint: 500 },
      { value: "1k_10k", label: "1,000 – 10,000", midpoint: 5000 },
      { value: "10k_50k", label: "10,000 – 50,000", midpoint: 25000 },
      { value: "50k_plus", label: "50,000+", midpoint: 75000 },
    ],
    categoryWeights: [],
  },
  {
    id: "monthly_signups",
    label: "Monthly free signups / trials",
    type: "band",
    bands: [
      { value: "under_50", label: "Under 50", midpoint: 25 },
      { value: "50_200", label: "50 – 200", midpoint: 125 },
      { value: "200_1000", label: "200 – 1,000", midpoint: 500 },
      { value: "1000_plus", label: "1,000+", midpoint: 2000 },
    ],
    categoryWeights: [],
  },
  withNotSure({
    id: "visitor_signup_rate",
    label: "Visitor-to-signup rate (%)",
    helpText: "% of website visitors who start a free trial or signup.",
    benchmark: "Typical SaaS: 2–5%",
    type: "percent",
    min: 0,
    max: 100,
    placeholder: "e.g. 3",
    scoreNumeric: (v) => lowerIsWorse(v, 3, 0.8),
    categoryWeights: [cw("acquisition", 1)],
  }),
  withNotSure({
    id: "trial_conversion_rate",
    label: "Trial-to-paid conversion rate (%)",
    benchmark: "Typical SaaS: 8–15%",
    type: "percent",
    min: 0,
    max: 100,
    placeholder: "e.g. 8",
    scoreNumeric: (v) => lowerIsWorse(v, 15, 3),
    categoryWeights: [cw("conversion", 1)],
  }),
  withNotSure({
    id: "monthly_churn_rate",
    label: "Monthly churn rate (%)",
    benchmark: "Healthy SaaS: under 3% monthly",
    type: "percent",
    min: 0,
    max: 100,
    placeholder: "e.g. 5",
    scoreNumeric: (v) => higherIsWorse(v, 2, 10),
    categoryWeights: [cw("retention", 1)],
  }),
  withNotSure({
    id: "failed_payment_rate",
    label: "Failed payment rate (%)",
    helpText: "Share of recurring charges that fail each month.",
    benchmark: "Typical: 1–3%",
    type: "percent",
    min: 0,
    max: 100,
    placeholder: "e.g. 3",
    scoreNumeric: (v) => higherIsWorse(v, 1, 8),
    categoryWeights: [cw("billing", 1)],
  }),
  {
    id: "retry_failed_payments",
    label: "Do you automatically retry failed payments?",
    type: "yesno",
    options: [
      { value: "yes", label: "Yes", riskScore: 10 },
      { value: "no", label: "No", riskScore: 85 },
    ],
    categoryWeights: [cw("billing", 1)],
  },
  {
    id: "arpu",
    label: "Average revenue per account (per month)",
    type: "band",
    bands: [
      { value: "under_50", label: "Under $50", midpoint: 29 },
      { value: "50_100", label: "$50 – $100", midpoint: 75 },
      { value: "100_300", label: "$100 – $300", midpoint: 150 },
      { value: "300_plus", label: "$300+", midpoint: 500 },
    ],
    categoryWeights: [],
  },
  {
    id: "demo_response_sla",
    label: "Average time to respond to demo or pricing requests",
    type: "select",
    benchmark: "Best-in-class: under 1 hour",
    options: [
      { value: "under_1h", label: "Under 1 hour", riskScore: 10 },
      { value: "1_4h", label: "1–4 hours", riskScore: 40 },
      { value: "4_24h", label: "4–24 hours", riskScore: 70 },
      { value: "over_24h", label: "Over 24 hours", riskScore: 95 },
    ],
    categoryWeights: [cw("response", 1)],
  },
  {
    id: "upsell_paths",
    label: "Upsell / cross-sell paths",
    type: "select",
    options: [
      { value: "strong", label: "Strong — multiple clear upgrade paths", riskScore: 10 },
      { value: "some", label: "Some — occasional offers", riskScore: 45 },
      { value: "none", label: "None — single plan only", riskScore: 90 },
    ],
    categoryWeights: [cw("expansion", 1)],
  },
];
