import type { Question } from "../types";
import { cw, higherIsWorse, lowerIsWorse } from "./helpers";
import { withNotSure } from "./shared";

export const serviceQuestions: Question[] = [
  {
    id: "biggest_frustration",
    label: "What's your single biggest growth frustration right now?",
    type: "select",
    qualitative: true,
    options: [
      { value: "getting_leads", label: "Not enough calls or leads", riskScore: 0 },
      { value: "booking_jobs", label: "Inquiries don't book or close", riskScore: 0 },
      { value: "repeat_business", label: "No repeat or referral business", riskScore: 0 },
      { value: "slow_response", label: "Too slow to respond / missed calls", riskScore: 0 },
      { value: "not_sure", label: "Not sure — show me everything", riskScore: 0 },
    ],
    categoryWeights: [],
  },
  {
    id: "monthly_leads",
    label: "Monthly inbound calls / leads",
    type: "band",
    bands: [
      { value: "under_30", label: "Under 30", midpoint: 15 },
      { value: "30_100", label: "30 – 100", midpoint: 60 },
      { value: "100_300", label: "100 – 300", midpoint: 180 },
      { value: "300_plus", label: "300+", midpoint: 450 },
    ],
    categoryWeights: [],
  },
  withNotSure({
    id: "missed_call_rate",
    label: "Missed call rate (%)",
    benchmark: "Healthy: under 5%",
    type: "percent",
    min: 0,
    max: 100,
    placeholder: "e.g. 15",
    scoreNumeric: (v) => higherIsWorse(v, 5, 30),
    categoryWeights: [cw("response", 1)],
  }),
  {
    id: "inquiry_response_time",
    label: "Average response time to new inquiries",
    type: "select",
    options: [
      { value: "under_15m", label: "Under 15 minutes", riskScore: 10 },
      { value: "15_60m", label: "15–60 minutes", riskScore: 35 },
      { value: "1_4h", label: "1–4 hours", riskScore: 60 },
      { value: "over_4h", label: "Over 4 hours", riskScore: 90 },
    ],
    categoryWeights: [cw("response", 1)],
  },
  {
    id: "online_booking",
    label: "How can customers book with you?",
    type: "select",
    options: [
      { value: "online_24_7", label: "Online booking 24/7", riskScore: 10 },
      { value: "online_business", label: "Online booking during business hours", riskScore: 30 },
      { value: "phone_only", label: "Phone or walk-in only", riskScore: 75 },
    ],
    categoryWeights: [cw("response", 0.5), cw("conversion", 0.5)],
  },
  withNotSure({
    id: "booking_rate",
    label: "Appointment booking rate (%)",
    helpText: "% of inquiries that book an appointment.",
    benchmark: "Typical: 40–55%",
    type: "percent",
    min: 0,
    max: 100,
    placeholder: "e.g. 40",
    scoreNumeric: (v) => lowerIsWorse(v, 55, 25),
    categoryWeights: [cw("conversion", 1)],
  }),
  withNotSure({
    id: "no_show_rate",
    label: "No-show rate (%)",
    helpText: "% of booked appointments that don't show up.",
    benchmark: "Typical: under 8%",
    type: "percent",
    min: 0,
    max: 100,
    placeholder: "e.g. 12",
    scoreNumeric: (v) => higherIsWorse(v, 8, 25),
    categoryWeights: [cw("conversion", 0.5), cw("billing", 0.5)],
  }),
  withNotSure({
    id: "quote_close_rate",
    label: "Quote-to-close rate (%)",
    benchmark: "Typical: 35–50%",
    type: "percent",
    min: 0,
    max: 100,
    placeholder: "e.g. 35",
    scoreNumeric: (v) => lowerIsWorse(v, 50, 20),
    categoryWeights: [cw("conversion", 1)],
  }),
  {
    id: "avg_job_value",
    label: "Average job value",
    type: "band",
    bands: [
      { value: "under_200", label: "Under $200", midpoint: 125 },
      { value: "200_500", label: "$200 – $500", midpoint: 350 },
      { value: "500_1500", label: "$500 – $1,500", midpoint: 900 },
      { value: "1500_plus", label: "$1,500+", midpoint: 2500 },
    ],
    categoryWeights: [],
  },
  {
    id: "quote_follow_up",
    label: "Do you follow up systematically after quotes?",
    type: "yesno",
    options: [
      { value: "yes", label: "Yes", riskScore: 15 },
      { value: "no", label: "No", riskScore: 85 },
    ],
    categoryWeights: [cw("conversion", 1)],
  },
  {
    id: "reactivate_customers",
    label: "Reactivate old leads or past customers?",
    type: "select",
    options: [
      { value: "systematically", label: "Systematically — scheduled outreach", riskScore: 10 },
      { value: "sometimes", label: "Sometimes", riskScore: 50 },
      { value: "never", label: "Never", riskScore: 90 },
    ],
    categoryWeights: [cw("retention", 0.7), cw("expansion", 0.3)],
  },
];
